/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database.tables.records;


import com.revolut.test.backend.ricardofuzeto.database.tables.PendingDeposit;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PendingDepositRecord extends UpdatableRecordImpl<PendingDepositRecord> implements Record1<String> {

    private static final long serialVersionUID = -493381286;

    /**
     * Setter for <code>pending_deposit.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pending_deposit.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PendingDeposit.PENDING_DEPOSIT.ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public PendingDepositRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public PendingDepositRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PendingDepositRecord
     */
    public PendingDepositRecord() {
        super(PendingDeposit.PENDING_DEPOSIT);
    }

    /**
     * Create a detached, initialised PendingDepositRecord
     */
    public PendingDepositRecord(String id) {
        super(PendingDeposit.PENDING_DEPOSIT);

        set(0, id);
    }
}
