/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database.tables.records;


import com.revolut.test.backend.ricardofuzeto.database.tables.TransferAttempt;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferAttemptRecord extends UpdatableRecordImpl<TransferAttemptRecord> implements Record3<String, Timestamp, UInteger> {

    private static final long serialVersionUID = -2047699493;

    /**
     * Setter for <code>transfer_attempt.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transfer_attempt.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transfer_attempt.date_of_transfer</code>.
     */
    public void setDateOfTransfer(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>transfer_attempt.date_of_transfer</code>.
     */
    public Timestamp getDateOfTransfer() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>transfer_attempt.result</code>.
     */
    public void setResult(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>transfer_attempt.result</code>.
     */
    public UInteger getResult() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Timestamp, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Timestamp, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TransferAttempt.TRANSFER_ATTEMPT.ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return TransferAttempt.TRANSFER_ATTEMPT.DATE_OF_TRANSFER;
    }

    @Override
    public Field<UInteger> field3() {
        return TransferAttempt.TRANSFER_ATTEMPT.RESULT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Timestamp component2() {
        return getDateOfTransfer();
    }

    @Override
    public UInteger component3() {
        return getResult();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Timestamp value2() {
        return getDateOfTransfer();
    }

    @Override
    public UInteger value3() {
        return getResult();
    }

    @Override
    public TransferAttemptRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public TransferAttemptRecord value2(Timestamp value) {
        setDateOfTransfer(value);
        return this;
    }

    @Override
    public TransferAttemptRecord value3(UInteger value) {
        setResult(value);
        return this;
    }

    @Override
    public TransferAttemptRecord values(String value1, Timestamp value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferAttemptRecord
     */
    public TransferAttemptRecord() {
        super(TransferAttempt.TRANSFER_ATTEMPT);
    }

    /**
     * Create a detached, initialised TransferAttemptRecord
     */
    public TransferAttemptRecord(String id, Timestamp dateOfTransfer, UInteger result) {
        super(TransferAttempt.TRANSFER_ATTEMPT);

        set(0, id);
        set(1, dateOfTransfer);
        set(2, result);
    }
}
