/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PendingWithdraw implements Serializable {

    private static final long serialVersionUID = -670174628;

    private String id;

    public PendingWithdraw() {}

    public PendingWithdraw(PendingWithdraw value) {
        this.id = value.id;
    }

    public PendingWithdraw(
        String id
    ) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PendingWithdraw (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
