/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transfer implements Serializable {

    private static final long serialVersionUID = -2028516450;

    private String   id;
    private String   sender;
    private String   receiver;
    private UInteger amount;
    private String   senderCurrency;
    private String   receiverCurrency;
    private Integer  retriesleft;

    public Transfer() {}

    public Transfer(Transfer value) {
        this.id = value.id;
        this.sender = value.sender;
        this.receiver = value.receiver;
        this.amount = value.amount;
        this.senderCurrency = value.senderCurrency;
        this.receiverCurrency = value.receiverCurrency;
        this.retriesleft = value.retriesleft;
    }

    public Transfer(
        String   id,
        String   sender,
        String   receiver,
        UInteger amount,
        String   senderCurrency,
        String   receiverCurrency,
        Integer  retriesleft
    ) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.amount = amount;
        this.senderCurrency = senderCurrency;
        this.receiverCurrency = receiverCurrency;
        this.retriesleft = retriesleft;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSender() {
        return this.sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public UInteger getAmount() {
        return this.amount;
    }

    public void setAmount(UInteger amount) {
        this.amount = amount;
    }

    public String getSenderCurrency() {
        return this.senderCurrency;
    }

    public void setSenderCurrency(String senderCurrency) {
        this.senderCurrency = senderCurrency;
    }

    public String getReceiverCurrency() {
        return this.receiverCurrency;
    }

    public void setReceiverCurrency(String receiverCurrency) {
        this.receiverCurrency = receiverCurrency;
    }

    public Integer getRetriesleft() {
        return this.retriesleft;
    }

    public void setRetriesleft(Integer retriesleft) {
        this.retriesleft = retriesleft;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transfer (");

        sb.append(id);
        sb.append(", ").append(sender);
        sb.append(", ").append(receiver);
        sb.append(", ").append(amount);
        sb.append(", ").append(senderCurrency);
        sb.append(", ").append(receiverCurrency);
        sb.append(", ").append(retriesleft);

        sb.append(")");
        return sb.toString();
    }
}
