/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database.tables;


import com.revolut.test.backend.ricardofuzeto.database.DefaultSchema;
import com.revolut.test.backend.ricardofuzeto.database.Indexes;
import com.revolut.test.backend.ricardofuzeto.database.Keys;
import com.revolut.test.backend.ricardofuzeto.database.tables.records.PendingDepositRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PendingDeposit extends TableImpl<PendingDepositRecord> {

    private static final long serialVersionUID = -1583577272;

    /**
     * The reference instance of <code>pending_deposit</code>
     */
    public static final PendingDeposit PENDING_DEPOSIT = new PendingDeposit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingDepositRecord> getRecordType() {
        return PendingDepositRecord.class;
    }

    /**
     * The column <code>pending_deposit.id</code>.
     */
    public final TableField<PendingDepositRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * Create a <code>pending_deposit</code> table reference
     */
    public PendingDeposit() {
        this(DSL.name("pending_deposit"), null);
    }

    /**
     * Create an aliased <code>pending_deposit</code> table reference
     */
    public PendingDeposit(String alias) {
        this(DSL.name(alias), PENDING_DEPOSIT);
    }

    /**
     * Create an aliased <code>pending_deposit</code> table reference
     */
    public PendingDeposit(Name alias) {
        this(alias, PENDING_DEPOSIT);
    }

    private PendingDeposit(Name alias, Table<PendingDepositRecord> aliased) {
        this(alias, aliased, null);
    }

    private PendingDeposit(Name alias, Table<PendingDepositRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PendingDeposit(Table<O> child, ForeignKey<O, PendingDepositRecord> key) {
        super(child, key, PENDING_DEPOSIT);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PENDING_DEPOSIT_PRIMARY);
    }

    @Override
    public UniqueKey<PendingDepositRecord> getPrimaryKey() {
        return Keys.KEY_PENDING_DEPOSIT_PRIMARY;
    }

    @Override
    public List<UniqueKey<PendingDepositRecord>> getKeys() {
        return Arrays.<UniqueKey<PendingDepositRecord>>asList(Keys.KEY_PENDING_DEPOSIT_PRIMARY);
    }

    @Override
    public List<ForeignKey<PendingDepositRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PendingDepositRecord, ?>>asList(Keys.PENDING_DEPOSIT_IBFK_1);
    }

    public Transfer transfer() {
        return new Transfer(this, Keys.PENDING_DEPOSIT_IBFK_1);
    }

    @Override
    public PendingDeposit as(String alias) {
        return new PendingDeposit(DSL.name(alias), this);
    }

    @Override
    public PendingDeposit as(Name alias) {
        return new PendingDeposit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingDeposit rename(String name) {
        return new PendingDeposit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingDeposit rename(Name name) {
        return new PendingDeposit(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
