/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.ricardofuzeto.database;


import com.revolut.test.backend.ricardofuzeto.database.tables.FlywaySchemaHistory;
import com.revolut.test.backend.ricardofuzeto.database.tables.PendingDeposit;
import com.revolut.test.backend.ricardofuzeto.database.tables.PendingWithdraw;
import com.revolut.test.backend.ricardofuzeto.database.tables.Transfer;
import com.revolut.test.backend.ricardofuzeto.database.tables.TransferAttempt;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>pending_deposit</code>.
     */
    public static final PendingDeposit PENDING_DEPOSIT = PendingDeposit.PENDING_DEPOSIT;

    /**
     * The table <code>pending_withdraw</code>.
     */
    public static final PendingWithdraw PENDING_WITHDRAW = PendingWithdraw.PENDING_WITHDRAW;

    /**
     * The table <code>transfer</code>.
     */
    public static final Transfer TRANSFER = Transfer.TRANSFER;

    /**
     * The table <code>transfer_attempt</code>.
     */
    public static final TransferAttempt TRANSFER_ATTEMPT = TransferAttempt.TRANSFER_ATTEMPT;
}
